//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace PWA.PineWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTwoNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback MultiplyTwoNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeadsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginLeadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMenuOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyToOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertLeadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::PWA.Properties.Settings.Default.PWA_PineWS_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AddTwoNumbersCompletedEventHandler AddTwoNumbersCompleted;
        
        /// <remarks/>
        public event MultiplyTwoNumbersCompletedEventHandler MultiplyTwoNumbersCompleted;
        
        /// <remarks/>
        public event GetLeadsCompletedEventHandler GetLeadsCompleted;
        
        /// <remarks/>
        public event LoginLeadCompletedEventHandler LoginLeadCompleted;
        
        /// <remarks/>
        public event GetMenuCompletedEventHandler GetMenuCompleted;
        
        /// <remarks/>
        public event InsertOrderCompletedEventHandler InsertOrderCompleted;
        
        /// <remarks/>
        public event GetOrderCountCompletedEventHandler GetOrderCountCompleted;
        
        /// <remarks/>
        public event CopyToOrderCompletedEventHandler CopyToOrderCompleted;
        
        /// <remarks/>
        public event ValidateLoginCompletedEventHandler ValidateLoginCompleted;
        
        /// <remarks/>
        public event InsertLeadCompletedEventHandler InsertLeadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTwoNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddTwoNumbers(int num1, int num2) {
            object[] results = this.Invoke("AddTwoNumbers", new object[] {
                        num1,
                        num2});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddTwoNumbersAsync(int num1, int num2) {
            this.AddTwoNumbersAsync(num1, num2, null);
        }
        
        /// <remarks/>
        public void AddTwoNumbersAsync(int num1, int num2, object userState) {
            if ((this.AddTwoNumbersOperationCompleted == null)) {
                this.AddTwoNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTwoNumbersOperationCompleted);
            }
            this.InvokeAsync("AddTwoNumbers", new object[] {
                        num1,
                        num2}, this.AddTwoNumbersOperationCompleted, userState);
        }
        
        private void OnAddTwoNumbersOperationCompleted(object arg) {
            if ((this.AddTwoNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTwoNumbersCompleted(this, new AddTwoNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MultiplyTwoNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MultiplyTwoNumbers(int num1, int num2) {
            object[] results = this.Invoke("MultiplyTwoNumbers", new object[] {
                        num1,
                        num2});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MultiplyTwoNumbersAsync(int num1, int num2) {
            this.MultiplyTwoNumbersAsync(num1, num2, null);
        }
        
        /// <remarks/>
        public void MultiplyTwoNumbersAsync(int num1, int num2, object userState) {
            if ((this.MultiplyTwoNumbersOperationCompleted == null)) {
                this.MultiplyTwoNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMultiplyTwoNumbersOperationCompleted);
            }
            this.InvokeAsync("MultiplyTwoNumbers", new object[] {
                        num1,
                        num2}, this.MultiplyTwoNumbersOperationCompleted, userState);
        }
        
        private void OnMultiplyTwoNumbersOperationCompleted(object arg) {
            if ((this.MultiplyTwoNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MultiplyTwoNumbersCompleted(this, new MultiplyTwoNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLeads", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lead[] GetLeads() {
            object[] results = this.Invoke("GetLeads", new object[0]);
            return ((Lead[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeadsAsync() {
            this.GetLeadsAsync(null);
        }
        
        /// <remarks/>
        public void GetLeadsAsync(object userState) {
            if ((this.GetLeadsOperationCompleted == null)) {
                this.GetLeadsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeadsOperationCompleted);
            }
            this.InvokeAsync("GetLeads", new object[0], this.GetLeadsOperationCompleted, userState);
        }
        
        private void OnGetLeadsOperationCompleted(object arg) {
            if ((this.GetLeadsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeadsCompleted(this, new GetLeadsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginLead", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lead LoginLead(string LeadPhone) {
            object[] results = this.Invoke("LoginLead", new object[] {
                        LeadPhone});
            return ((Lead)(results[0]));
        }
        
        /// <remarks/>
        public void LoginLeadAsync(string LeadPhone) {
            this.LoginLeadAsync(LeadPhone, null);
        }
        
        /// <remarks/>
        public void LoginLeadAsync(string LeadPhone, object userState) {
            if ((this.LoginLeadOperationCompleted == null)) {
                this.LoginLeadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginLeadOperationCompleted);
            }
            this.InvokeAsync("LoginLead", new object[] {
                        LeadPhone}, this.LoginLeadOperationCompleted, userState);
        }
        
        private void OnLoginLeadOperationCompleted(object arg) {
            if ((this.LoginLeadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginLeadCompleted(this, new LoginLeadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MenuItems[] GetMenu() {
            object[] results = this.Invoke("GetMenu", new object[0]);
            return ((MenuItems[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMenuAsync() {
            this.GetMenuAsync(null);
        }
        
        /// <remarks/>
        public void GetMenuAsync(object userState) {
            if ((this.GetMenuOperationCompleted == null)) {
                this.GetMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMenuOperationCompleted);
            }
            this.InvokeAsync("GetMenu", new object[0], this.GetMenuOperationCompleted, userState);
        }
        
        private void OnGetMenuOperationCompleted(object arg) {
            if ((this.GetMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMenuCompleted(this, new GetMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertOrder(OrderItems newOrder) {
            object[] results = this.Invoke("InsertOrder", new object[] {
                        newOrder});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertOrderAsync(OrderItems newOrder) {
            this.InsertOrderAsync(newOrder, null);
        }
        
        /// <remarks/>
        public void InsertOrderAsync(OrderItems newOrder, object userState) {
            if ((this.InsertOrderOperationCompleted == null)) {
                this.InsertOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertOrderOperationCompleted);
            }
            this.InvokeAsync("InsertOrder", new object[] {
                        newOrder}, this.InsertOrderOperationCompleted, userState);
        }
        
        private void OnInsertOrderOperationCompleted(object arg) {
            if ((this.InsertOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertOrderCompleted(this, new InsertOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetOrderCount(int LeadID) {
            object[] results = this.Invoke("GetOrderCount", new object[] {
                        LeadID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderCountAsync(int LeadID) {
            this.GetOrderCountAsync(LeadID, null);
        }
        
        /// <remarks/>
        public void GetOrderCountAsync(int LeadID, object userState) {
            if ((this.GetOrderCountOperationCompleted == null)) {
                this.GetOrderCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderCountOperationCompleted);
            }
            this.InvokeAsync("GetOrderCount", new object[] {
                        LeadID}, this.GetOrderCountOperationCompleted, userState);
        }
        
        private void OnGetOrderCountOperationCompleted(object arg) {
            if ((this.GetOrderCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderCountCompleted(this, new GetOrderCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CopyToOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CopyToOrder(Orders newOrderHistory) {
            object[] results = this.Invoke("CopyToOrder", new object[] {
                        newOrderHistory});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CopyToOrderAsync(Orders newOrderHistory) {
            this.CopyToOrderAsync(newOrderHistory, null);
        }
        
        /// <remarks/>
        public void CopyToOrderAsync(Orders newOrderHistory, object userState) {
            if ((this.CopyToOrderOperationCompleted == null)) {
                this.CopyToOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyToOrderOperationCompleted);
            }
            this.InvokeAsync("CopyToOrder", new object[] {
                        newOrderHistory}, this.CopyToOrderOperationCompleted, userState);
        }
        
        private void OnCopyToOrderOperationCompleted(object arg) {
            if ((this.CopyToOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyToOrderCompleted(this, new CopyToOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidateLogin(string PhoneNumber) {
            object[] results = this.Invoke("ValidateLogin", new object[] {
                        PhoneNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string PhoneNumber) {
            this.ValidateLoginAsync(PhoneNumber, null);
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string PhoneNumber, object userState) {
            if ((this.ValidateLoginOperationCompleted == null)) {
                this.ValidateLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateLoginOperationCompleted);
            }
            this.InvokeAsync("ValidateLogin", new object[] {
                        PhoneNumber}, this.ValidateLoginOperationCompleted, userState);
        }
        
        private void OnValidateLoginOperationCompleted(object arg) {
            if ((this.ValidateLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateLoginCompleted(this, new ValidateLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertLead", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertLead(Lead lead) {
            object[] results = this.Invoke("InsertLead", new object[] {
                        lead});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertLeadAsync(Lead lead) {
            this.InsertLeadAsync(lead, null);
        }
        
        /// <remarks/>
        public void InsertLeadAsync(Lead lead, object userState) {
            if ((this.InsertLeadOperationCompleted == null)) {
                this.InsertLeadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLeadOperationCompleted);
            }
            this.InvokeAsync("InsertLead", new object[] {
                        lead}, this.InsertLeadOperationCompleted, userState);
        }
        
        private void OnInsertLeadOperationCompleted(object arg) {
            if ((this.InsertLeadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLeadCompleted(this, new InsertLeadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lead {
        
        private int zipField;
        
        private string cityField;
        
        private string stateField;
        
        private string phoneField;
        
        private int idField;
        
        private string nameField;
        
        private string addressField;
        
        /// <remarks/>
        public int Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Orders {
        
        private int orderIDField;
        
        private decimal totalField;
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderItems {
        
        private int orderIDField;
        
        private int menuIDField;
        
        private int quantityField;
        
        private decimal totalUnitPriceField;
        
        private decimal leadIDField;
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public int MenuID {
            get {
                return this.menuIDField;
            }
            set {
                this.menuIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalUnitPrice {
            get {
                return this.totalUnitPriceField;
            }
            set {
                this.totalUnitPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal LeadID {
            get {
                return this.leadIDField;
            }
            set {
                this.leadIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MenuItems {
        
        private string orderInfoField;
        
        private int itemIdField;
        
        private string itemNameField;
        
        private string descriptionField;
        
        private decimal priceField;
        
        /// <remarks/>
        public string OrderInfo {
            get {
                return this.orderInfoField;
            }
            set {
                this.orderInfoField = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AddTwoNumbersCompletedEventHandler(object sender, AddTwoNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTwoNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTwoNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void MultiplyTwoNumbersCompletedEventHandler(object sender, MultiplyTwoNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultiplyTwoNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MultiplyTwoNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetLeadsCompletedEventHandler(object sender, GetLeadsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lead[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lead[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginLeadCompletedEventHandler(object sender, LoginLeadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginLeadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginLeadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lead Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lead)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetMenuCompletedEventHandler(object sender, GetMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MenuItems[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MenuItems[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void InsertOrderCompletedEventHandler(object sender, InsertOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetOrderCountCompletedEventHandler(object sender, GetOrderCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void CopyToOrderCompletedEventHandler(object sender, CopyToOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyToOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CopyToOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ValidateLoginCompletedEventHandler(object sender, ValidateLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void InsertLeadCompletedEventHandler(object sender, InsertLeadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLeadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertLeadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591